version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules